# Generated by Django 5.0.1 on 2024-01-13 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Armazem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='posicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoques', to='Armazem.posicao'),
        ),
        migrations.AlterField(
            model_name='item',
            name='movimentacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='Armazem.movimentacao'),
        ),
    ]
