# Generated by Django 5.0.1 on 2024-01-13 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Armazem', '0002_alter_estoque_posicao_alter_item_movimentacao'),
        ('Produto', '0003_alter_produto_especificacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='posicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Armazem.posicao'),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoques', to='Produto.produto'),
        ),
        migrations.AlterField(
            model_name='item',
            name='codigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='Produto.produto'),
        ),
    ]
