# Generated by Django 5.0.1 on 2024-01-12 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Familia',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank='False', max_length=30, unique=True)),
                ('codigo_Aaxiliar', models.CharField(blank='False', max_length=30, unique=True)),
                ('descricao', models.CharField(blank='False', max_length=100)),
                ('unidade', models.CharField(blank='False', choices=[('Cj', 'Conjunto'), ('Cx', 'Caixa'), ('Dz', 'Dúzia'), ('Fd', 'Fardo'), ('Fl', 'Folha'), ('Gl', 'Galão'), ('Lt', 'Lote'), ('Jg', 'Jogo'), ('Kg', 'Kilograma'), ('L', 'Litro'), ('Lta', 'Lata'), ('M', 'Metro'), ('Mil', 'Milheiro'), ('Par', 'Par'), ('Pct', 'Pacote'), ('Pç', 'Peça'), ('Res', 'Resma'), ('Rl', 'Rolo'), ('Ton', 'Tonelada'), ('Und', 'Unidade'), ('Vd', 'Vidro'), ('M³', 'Metro_cubico'), ('M²', 'Metro_quadrado')], max_length=30)),
                ('tipo_item', models.CharField(blank='False', max_length=30)),
                ('ativo', models.CharField(blank='False', choices=[('Sim', 'Sim'), ('Não', 'Nao')], max_length=30)),
                ('especificacao', models.CharField(default='', max_length=200)),
                ('fornecedor', models.CharField(blank='True', max_length=200, null=True)),
                ('observacao', models.CharField(default='', max_length=200)),
                ('imagem', models.ImageField(default='', upload_to='')),
                ('tempo_validade', models.IntegerField(default=0)),
                ('comprimento', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('largura', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('altura', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('prazo_frete', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('peso', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('saldo', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('estoque_minimo', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('estoque_maximo', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('estoque_seguranca', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Produto.familia')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
    ]
