# Generated by Django 5.0.1 on 2024-01-13 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produto', '0002_alter_produto_ativo_alter_produto_imagem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='especificacao',
            field=models.TextField(blank=True, default='', max_length=200, null=True),
        ),
    ]
